### ISSUE TITLE
universities 的链接 404了

### ISSUE THREAD

**Issue by lei946** [NoHeartPen/awesome_japanese_study_tools#1]
universities 的链接 404了

**Comment by NoHeartPen** [comment]
不好意思，universities 部分被我鸽掉了233：主要是自己比较忙，这个项目也没什么关注者，所以这个部分的内容一直没有更新，而且自己也不知道要写什么。作为第一个问这个问题的同学，你可以描述下你期待看到的内容么?

可以参考如下文档：

https://www.yuque.com/noheartpen/tnxvz0/sq6nl7?singleDoc# 《SISU_关于系群的几点建议》（这里谈了我个人的一些想法）

https://www.yuque.com/noheartpen/pm4130/vqnqua?singleDoc# 《SISU_川外图书馆漫游指南》（介绍校图书馆适合本科生阅读的书籍）

**Comment by NoHeartPen** [comment]
已修复
